version: "3.3"
services:
  # Ocelot services
  admin:
    image: ocelot-admin
    build:
      context: .
      dockerfile: admin/Dockerfile
      cache_from:
        - golang:1.9-alpine
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - "/etc/letsencrypt/live/ocelot.hq.l11.com/privkey.pem:/etc/letsencrypt/live/ocelot.hq.l11.com/privkey.pem"
    ports:
      - "10000:10000"
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
      CONSUL_HOST: http://172.18.0.1
      VAULT_ADDR: http://172.18.0.1:8200
      NSQLOOKUPD_IP: 172.18.0.1
      NSQD_IP: 172.18.0.1
  hookhandler:
    image: ocelot-hookhandler
    build:
      context: .
      dockerfile: hookhandler/Dockerfile
      cache_from:
        - golang:1.9-alpine
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "8088:8088"
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_ADDR: http://172.18.0.1:8200
      CONSUL_HOST: http://172.18.0.1
      LOG_LEVEL: debug
      NSQD_IP: 172.17.0.1
      NSQLOOKUPD_IP: 172.17.0.1
  werker:
    image: ocelot-werker
    build:
      context: .
      dockerfile: werker/Dockerfile
      cache_from:
        - golang:1.9-alpine
    environment:
      VAULT_ADDR: http://172.18.0.1:8200
      NSQD_IP: 172.17.0.1
      NSQLOOKUPD_IP: 172.17.0.1
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
networks:
  default:
    external:
      name: ocelot_default
