version: "3.3"
services:
  # Ocelot services
  admin:
    image: ocelot-admin
    build:
      context: .
      dockerfile: admin/Dockerfile
      cache_from:
        - golang:1.9-alpine
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      VAULT_TOKEN: e92136aa-93c6-6062-b724-cba19fd775fe
  hookhandler:
    image: ocelot-hookhandler
    build:
      context: .
      dockerfile: hookhandler/Dockerfile
      cache_from:
        - golang:1.9-alpine
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "8088:8088"
    environment:
      VAULT_TOKEN: e92136aa-93c6-6062-b724-cba19fd775fe
      VAULT_ADDR: http://172.18.0.1:8200
  werker:
    image: ocelot-werker
    build:
      context: .
      dockerfile: werker/Dockerfile
      cache_from:
        - golang:1.9-alpine
    environment:
      VAULT_ADDR: http://172.18.0.1:8200
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
networks:
  default:
    external:
      name: ocelot_default