version: "3.3"
services:
  # Ocelot services
  admin:
    image: ocelot-admin
    build:
      context: .
      dockerfile: admin/Dockerfile
      cache_from:
        - golang:1.9-alpine
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "10000:10000"
    environment:
      VAULT_TOKEN: 4b7b5f11-7bd1-80fa-cdaa-b950e9bd502d
      CONSUL_HOST: 172.18.0.1
  hookhandler:
    image: ocelot-hookhandler
    build:
      context: .
      dockerfile: hookhandler/Dockerfile
      cache_from:
        - golang:1.9-alpine
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "8088:8088"
    environment:
      VAULT_TOKEN: 4b7b5f11-7bd1-80fa-cdaa-b950e9bd502d
      VAULT_ADDR: http://172.18.0.1:8200
      CONSUL_HOST: 172.18.0.1
  werker:
    image: ocelot-werker
    build:
      context: .
      dockerfile: werker/Dockerfile
      cache_from:
        - golang:1.9-alpine
    environment:
      VAULT_ADDR: http://172.18.0.1:8200
      CONSUL_HOST: 172.18.0.1
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
networks:
  default:
    external:
      name: ocelot_default
