version: "3.3"
services:
  # Ocelot services
  admin:
    image: ocelot-admin
    container_name: admin
    command: /admin -log-level=debug
    build:
      context: .
      dockerfile: cmd/admin/Dockerfile
      cache_from:
        - golang:1.9-alpine
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "10000:10000"
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_ADDR: http://vault:8200
      CONSUL_HOST: http://consul
      NSQLOOKUPD_IP: nsqlookupd
      NSQD_IP: nsqd

  hookhandler:
    image: ocelot-hookhandler
    container_name: hookhandler
    command: /hookhandler 
    build:
      context: .
      dockerfile: cmd/hookhandler/Dockerfile
      cache_from:
        - golang:1.9-alpine
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "8088:8088"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_ADDR: http://vault:8200
      CONSUL_HOST: http://consul
      LOG_LEVEL: debug
      NSQD_IP: nsqd
      NSQLOOKUPD_IP: nsqlookupd

  werker:
    image: ocelot-werker
    container_name: werker
    command: /werker -log-level debug
    build:
      context: .
      dockerfile: cmd/werker/Dockerfile
      cache_from:
        - golang:1.9-alpine
    ports:
      - "9090:9090"
      - "9099:9099"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_ADDR: http://vault:8200
      CONSUL_HTTP_ADDR: http://consul:8500
      CONSUL_HOST: consul
      NSQD_IP: nsdq
      NSQLOOKUPD_IP: nsqlookupd
      REGISTER_IP: 10.1.62.38
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  poller:
    image: ocelot-poller
    container_name: poller
    build:
      context: .
      dockerfile: cmd/poller/Dockerfile
      cache_from:
        - golang:1.9-alpine
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_ADDR: http://vault:8200
      CONSUL_HTTP_ADDR: http://consul:8500
      CONSUL_HOST: consul
      NSQD_IP: nsqd
      NSQLOOKUPD_IP: nsqlookupd
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  default:
    external:
      name: ocelot
