version: "3.3"
services:
#  # Copied directly from ./docs/docker-compose/vault-consul/docker-compose.yml, with volume paths slightly modified, and with logging
#  consul:
#    image: consul:1.0.0
#    hostname: consul
#    command: a
#    ports:
#      - 8400:8400
#      - 8500:8500
#      - 8600:53/udp
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "200k"
#        max-file: "10"
#  vault:
#    image: vault
#    hostname: vault
#    environment:
#      VAULT_ADDR: http://127.0.0.1:8200
#    ports:
#      - 8200:8200
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "200k"
#        max-file: "10"
#    volumes:
#      - ./docs/docker-compose/vault-consul/tools/wait-for-it.sh:/wait-for-it.sh
#      - ./docs/docker-compose/vault-consul/config/vault:/config
#      - ./docs/docker-compose/vault-consul/config/vault/policies:/policies
#    entrypoint: /wait-for-it.sh -t 20 -h 172.18.0.1 -p 8500 -s -- vault server -config=/config/with-consul.hcl

  # Copied directly from ./util/nsqpb/docker-compose.yml, modified with logging
  nsqlookupd:
    image: nsqio/nsq
    command: >
      /nsqlookupd
      -broadcast-address localhost:4160
    ports:
      - 4160:4160
      - 4161:4161
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  nsqd:
    image: nsqio/nsq
    command: >
      /nsqd
      -broadcast-address localhost
      -lookupd-tcp-address nsqlookupd:4160
    ports:
      - 4150:4150
      - 4151:4151
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  nsqadmin:
    image: nsqio/nsq
    command: >
      /nsqadmin
      -nsqd-http-address nsqd:4151
    ports:
      - 4171:4171
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
