image: jessishank/ocelot-build:kill.6
buildTool: go
branches:
  - ALL
env:
  - "OCELOT_PATH=src/bitbucket.org/level11consulting/ocelot"
stages:
  - name: be_useful
    script:
      - echo "building $BUILD_ID with has $GIT_HASH"
  - name: go_stuff
    script:
      - cp -r $GOPATH/$OCELOT_PATH/vendor .
      - rm -rf $GOPATH/$OCELOT_PATH/* && cp -r . $GOPATH/$OCELOT_PATH
  - name: testing
    env:
      - "BUILDSERVERHACK=0"
    script:
      - cd $GOPATH/$OCELOT_PATH
      - go test ./... -cover -short
  - name: build
    script:
      - cd $GOPATH/$OCELOT_PATH
      - scripts/build-release-server.sh
