image: docker.metaverse.l11.com/alpine:latest
buildTool: go
branches:
  - ALL
env:
  - "OCELOT_PATH=src/bitbucket.org/level11consulting/ocelot"
stages:
  - name: testing
    env:
      - "BUILDSERVERHACK=0"
    script:
      - docker pull alpine:latest
      - docker tag alpine:latest jessishank/alpine:latest
      - docker push jessishank/alpine:latest 

  - name: build
    script:
      - docker pull alpine:latest
      - docker tag alpine:latest docker.metaverse.l11.com/alpine:latest
      - docker push docker.metaverse.l11.com/alpine:latest
