image: golang:1.9
buildTool: go
branches:
  - ALL
stages:
  - name: echoenvars
    script:
      - echo "WOWOWOWOW WE ARE ON $BUILD_ID"
  - name: testing
    script:
      - mkdir -p $GOPATH/src/bitbucket.org/level11consulting/ocelot
      - cp -r /$GIT_HASH/ /$GOPATH/src/bitbucket.org/level11consulting/ocelot
      - cd /$GOPATH/src/bitbucket.org/level11consulting/ocelot
      - go get -v -u github.com/golang/dep/cmd/dep
      - ssh -o "StrictHostKeyChecking no" git@bitbucket.org
      - dep ensure -v
      - ./run-tests.sh
  - name: build
    script:
      - cd $GOPATH/src/bitbucket.org/level11consulting/ocelot
      - ./build-release.sh
