image: jessishank/dockercomposegit
buildTool: go
branches:
  - nexus
stages:
  - name: tag ocelot builder for local use
    script:
      - docker pull jessishank/ocelot-build
      - docker tag jessishank/ocelot-build ocelot-build:latest
  - name: build
    script:
      - docker-compose build