image: golang:1.9
buildTool: go
branches:
  - master
stages:
  - name: set_me_up_giiiiirl
    script:
      - cd $GOPATH/src
      - go get github.com/golang/dep/cmd/dep
      - cd -
      - dep ensure -v
      - ./run-tests.sh
  - name: build
    script:
      - ./build-release.sh
