image: jessishank/ocelot-build:cheese
buildTool: go
branches:
  - ALL
stages:
  - name: be_useful
    script:
      - echo "building $BUILD_ID with has $GIT_HASH"
  - name: testing
    env:
      - "BUILDSERVERHACK=0"
    script:
      - cp -r $GOPATH/src/bitbucket.org/level11consulting/ocelot/vendor .
      - ./run-tests.sh
  - name: build
    script:
      - cd $GOPATH/src/bitbucket.org/level11consulting/ocelot
      - ./build-release.sh
