image: jessishank/ocelot-build
buildTool: go
branches:
  - <all>
stages:
  - name: build
    script:
      - go install ./...
  - name: test
    script:
      - go test ./...
  - name: upload
    script:
      - mvn deploy
  - name: deploy
      trigger:
        commit:
          - QA_READY
        branches:
          - master
          - staging
      script:
        - ./push-deploy.sh target/app*.jar
#  - name: integration
#    script: