image: golang:1.9
buildTool: go
branches:
  - ALL
stages:
  - name: be_useful
    script:
      - echo "building $BUILD_ID with has $GIT_HASH"
  - name: testing
    script:
      - mkdir -p $GOPATH/src/bitbucket.org/level11consulting/ocelot
      - cp -r * $GOPATH/src/bitbucket.org/level11consulting/ocelot
      - cp -r .git* $GOPATH/src/bitbucket.org/level11consulting/ocelot
      - cd $GOPATH/src/bitbucket.org/level11consulting/ocelot
      - go get -v -u github.com/golang/dep/cmd/dep
      - ssh -o "StrictHostKeyChecking no" git@bitbucket.org
      - dep ensure -v
      - ./run-tests.sh
  - name: build
    script:
      - cd $GOPATH/src/bitbucket.org/level11consulting/ocelot
      - ./build-release.sh
