image: golang:1.9
buildTool: go
branches:
  - low_hanging_fruits
  - master
stages:
  - name: testingg
    script:
      - mkdir -p $GOPATH/src/mah_code
      - cp -r * $GOPATH/src/mah_code
      - cd $GOPATH/src/mah_code
      - go get -v -u github.com/golang/dep/cmd/dep
      - ssh -o "StrictHostKeyChecking no" git@bitbucket.org
      - dep ensure -v
      - ./run-tests.sh
  - name: build
    script:
      - cd $GOPATH/src/mah_code
      - ./build-release.sh
