image: golang:1.9-alpine
buildTool: go
branches:
  - master
stages:
  - name: set_me_up_giiiiirl
    script:
      - dep ensure -v
      - ./run-tests.sh
  - name: build
    script:
      - ./build-release.sh