version: "3.3"
services:
  # Copied directly from ./util/nsqpb/docker-compose.yml, modified with logging
  nsqlookupd:
    image: nsqio/nsq
    command: >
      /nsqlookupd
      -broadcast-address localhost:4160
    ports:
      - 4160:4160
      - 4161:4161
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  nsqd:
    image: nsqio/nsq
    command: >
      /nsqd
      -broadcast-address 10.1.72.232
      -lookupd-tcp-address nsqlookupd:4160
    ports:
      - 4150:4150
      - 4151:4151
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
#  nsqadmin:
#    image: nsqio/nsq
#    command: >
#      /nsqadmin
#      -nsqd-http-address nsqd:4151
#    ports:
#      - 4171:4171
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "200k"
#        max-file: "10"
