version: '3.1'
services:
  hookhandler:
    image: ocelot-hookhandler
    build:
      context: ..
      dockerfile: hookhandler/Dockerfile
      cache_from:
        - golang:1.9-alpine
    environment:
      VAULT_TOKEN: secrets? ooowee
