version: "3.3"
services:
  # Copied directly from ./docs/docker-compose/vault-consul/docker-compose.yml, with volume paths slightly modified, and with logging
  consul:
    image: consul:1.0.0
    container_name: consul
    hostname: consul
    command: agent -dev -client 0.0.0.0
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:53/udp
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
networks:
  default:
    external:
      name: ocelot
