vcs:
    - clientId: QEBYwP5cKAC3ykhau4
      clientSecret: gKY2S3NGnFzJKBtUTGjQKc4UNvQqa2Vb
      tokenURL: https://bitbucket.org/site/oauth2/access_token
      acctName: jessishank
      type: bitbucket