// Code generated by protoc-gen-go. DO NOT EDIT.
// source: guideocelot.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf2 "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CredType int32

const (
	CredType_NIL_CT CredType = 0
	CredType_VCS    CredType = 1
	CredType_REPO   CredType = 2
	CredType_K8S    CredType = 3
)

var CredType_name = map[int32]string{
	0: "NIL_CT",
	1: "VCS",
	2: "REPO",
	3: "K8S",
}
var CredType_value = map[string]int32{
	"NIL_CT": 0,
	"VCS":    1,
	"REPO":   2,
	"K8S":    3,
}

func (x CredType) String() string {
	return proto.EnumName(CredType_name, int32(x))
}
func (CredType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type SubCredType int32

const (
	SubCredType_NIL_SCT   SubCredType = 0
	SubCredType_BITBUCKET SubCredType = 1
	SubCredType_GITHUB    SubCredType = 2
	SubCredType_NEXUS     SubCredType = 3
	SubCredType_MAVEN     SubCredType = 4
	SubCredType_DOCKER    SubCredType = 5
	SubCredType_KUBECONF  SubCredType = 6
)

var SubCredType_name = map[int32]string{
	0: "NIL_SCT",
	1: "BITBUCKET",
	2: "GITHUB",
	3: "NEXUS",
	4: "MAVEN",
	5: "DOCKER",
	6: "KUBECONF",
}
var SubCredType_value = map[string]int32{
	"NIL_SCT":   0,
	"BITBUCKET": 1,
	"GITHUB":    2,
	"NEXUS":     3,
	"MAVEN":     4,
	"DOCKER":    5,
	"KUBECONF":  6,
}

func (x SubCredType) String() string {
	return proto.EnumName(SubCredType_name, int32(x))
}
func (SubCredType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type BuildReq struct {
	// acctRepo is the ocelot account to which the creds are uploaded and the repository you wish to operate on, in the form account/repo
	AcctRepo string `protobuf:"bytes,1,opt,name=acctRepo" json:"acctRepo,omitempty"`
	// hash is the git hash to trigger.
	Hash string `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	// branch is the branch that corresponds to the git hash. if the git hash has never been built by ocelot, this field is required.
	Branch string `protobuf:"bytes,3,opt,name=branch" json:"branch,omitempty"`
}

func (m *BuildReq) Reset()                    { *m = BuildReq{} }
func (m *BuildReq) String() string            { return proto.CompactTextString(m) }
func (*BuildReq) ProtoMessage()               {}
func (*BuildReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *BuildReq) GetAcctRepo() string {
	if m != nil {
		return m.AcctRepo
	}
	return ""
}

func (m *BuildReq) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BuildReq) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

type AllCredsWrapper struct {
	// All repository credentials for integrations
	// @inject_tag: yaml:"repoCreds"
	RepoCreds *RepoCredWrapper `protobuf:"bytes,1,opt,name=repoCreds" json:"repoCreds,omitempty" yaml:"repoCreds"`
	// All VCS credentials for building
	// @inject_tag: yaml:"vcsCreds"
	VcsCreds *CredWrapper `protobuf:"bytes,3,opt,name=vcsCreds" json:"vcsCreds,omitempty" yaml:"vcsCreds"`
}

func (m *AllCredsWrapper) Reset()                    { *m = AllCredsWrapper{} }
func (m *AllCredsWrapper) String() string            { return proto.CompactTextString(m) }
func (*AllCredsWrapper) ProtoMessage()               {}
func (*AllCredsWrapper) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *AllCredsWrapper) GetRepoCreds() *RepoCredWrapper {
	if m != nil {
		return m.RepoCreds
	}
	return nil
}

func (m *AllCredsWrapper) GetVcsCreds() *CredWrapper {
	if m != nil {
		return m.VcsCreds
	}
	return nil
}

// just a container for a list of VCSCreds
type CredWrapper struct {
	Vcs []*VCSCreds `protobuf:"bytes,2,rep,name=vcs" json:"vcs,omitempty"`
}

func (m *CredWrapper) Reset()                    { *m = CredWrapper{} }
func (m *CredWrapper) String() string            { return proto.CompactTextString(m) }
func (*CredWrapper) ProtoMessage()               {}
func (*CredWrapper) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *CredWrapper) GetVcs() []*VCSCreds {
	if m != nil {
		return m.Vcs
	}
	return nil
}

type SSHKeyWrapper struct {
	// account name to associate ssh key with
	AcctName string `protobuf:"bytes,1,opt,name=acctName" json:"acctName,omitempty"`
	// the contents of the private key
	PrivateKey []byte      `protobuf:"bytes,2,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	SubType    SubCredType `protobuf:"varint,10,opt,name=subType,enum=models.SubCredType" json:"subType,omitempty"`
}

func (m *SSHKeyWrapper) Reset()                    { *m = SSHKeyWrapper{} }
func (m *SSHKeyWrapper) String() string            { return proto.CompactTextString(m) }
func (*SSHKeyWrapper) ProtoMessage()               {}
func (*SSHKeyWrapper) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *SSHKeyWrapper) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *SSHKeyWrapper) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *SSHKeyWrapper) GetSubType() SubCredType {
	if m != nil {
		return m.SubType
	}
	return SubCredType_NIL_SCT
}

type VCSCreds struct {
	// clientId is generated by creating an oAuth consumer in bitbucket. it is required to generate tokens.
	// @inject_tag: yaml:"clientId"
	ClientId string `protobuf:"bytes,1,opt,name=clientId" json:"clientId,omitempty" yaml:"clientId"`
	// clientSecret is generated by creating an oAuth consumer in bitbucket. it is required to generate tokens.
	// @inject_tag: yaml:"clientSecret"
	ClientSecret string `protobuf:"bytes,2,opt,name=clientSecret" json:"clientSecret,omitempty" yaml:"clientSecret"`
	// identifier is the name the user calls teh credential set
	Identifier string `protobuf:"bytes,8,opt,name=identifier" json:"identifier,omitempty"`
	// tokenUrl is the url at which to retrieve the token
	// @inject_tag: yaml:"tokenURL"
	TokenURL string `protobuf:"bytes,3,opt,name=tokenURL" json:"tokenURL,omitempty" yaml:"tokenURL"`
	// @inject_tag: yaml:"acctName"
	// acctName is the account to associate the VCSCred with. Must be the account name of the owner of the repository they wish to track (ie level11consulting)
	AcctName string `protobuf:"bytes,4,opt,name=acctName" json:"acctName,omitempty" yaml:"acctName"`
	// just a string that says whether or not there is an ssh key on file
	// @inject_tag: yaml:"sshFileLoc"
	SshFileLoc string `protobuf:"bytes,6,opt,name=sshFileLoc" json:"sshFileLoc,omitempty" yaml:"sshFileLoc"`
	// @inject_tag: yaml:"subType"
	SubType SubCredType `protobuf:"varint,10,opt,name=subType,enum=models.SubCredType" json:"subType,omitempty" yaml:"subType"`
}

func (m *VCSCreds) Reset()                    { *m = VCSCreds{} }
func (m *VCSCreds) String() string            { return proto.CompactTextString(m) }
func (*VCSCreds) ProtoMessage()               {}
func (*VCSCreds) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *VCSCreds) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *VCSCreds) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *VCSCreds) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *VCSCreds) GetTokenURL() string {
	if m != nil {
		return m.TokenURL
	}
	return ""
}

func (m *VCSCreds) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *VCSCreds) GetSshFileLoc() string {
	if m != nil {
		return m.SshFileLoc
	}
	return ""
}

func (m *VCSCreds) GetSubType() SubCredType {
	if m != nil {
		return m.SubType
	}
	return SubCredType_NIL_SCT
}

// container for list of repo creds
type RepoCredWrapper struct {
	Repo []*RepoCreds `protobuf:"bytes,3,rep,name=repo" json:"repo,omitempty"`
}

func (m *RepoCredWrapper) Reset()                    { *m = RepoCredWrapper{} }
func (m *RepoCredWrapper) String() string            { return proto.CompactTextString(m) }
func (*RepoCredWrapper) ProtoMessage()               {}
func (*RepoCredWrapper) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *RepoCredWrapper) GetRepo() []*RepoCreds {
	if m != nil {
		return m.Repo
	}
	return nil
}

type RepoCreds struct {
	// username of repository
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	// password of repository
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	// @inject_tag: yaml:"repoUrl"
	RepoUrl    string `protobuf:"bytes,6,opt,name=repoUrl" json:"repoUrl,omitempty" yaml:"repoUrl"`
	Identifier string `protobuf:"bytes,8,opt,name=identifier" json:"identifier,omitempty"`
	// @inject_tag: yaml:"acctName"
	// account name (same as from vcs)
	AcctName string `protobuf:"bytes,4,opt,name=acctName" json:"acctName,omitempty" yaml:"acctName"`
	// @inject_tag: yaml:"subType"
	SubType SubCredType `protobuf:"varint,10,opt,name=subType,enum=models.SubCredType" json:"subType,omitempty" yaml:"subType"`
}

func (m *RepoCreds) Reset()                    { *m = RepoCreds{} }
func (m *RepoCreds) String() string            { return proto.CompactTextString(m) }
func (*RepoCreds) ProtoMessage()               {}
func (*RepoCreds) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *RepoCreds) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RepoCreds) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RepoCreds) GetRepoUrl() string {
	if m != nil {
		return m.RepoUrl
	}
	return ""
}

func (m *RepoCreds) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *RepoCreds) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *RepoCreds) GetSubType() SubCredType {
	if m != nil {
		return m.SubType
	}
	return SubCredType_NIL_SCT
}

type K8SCreds struct {
	AcctName    string `protobuf:"bytes,1,opt,name=acctName" json:"acctName,omitempty"`
	K8SContents string `protobuf:"bytes,2,opt,name=k8sContents" json:"k8sContents,omitempty"`
	Identifier  string `protobuf:"bytes,3,opt,name=identifier" json:"identifier,omitempty"`
	// @inject_tag: yaml:"subType"
	SubType SubCredType `protobuf:"varint,5,opt,name=subType,enum=models.SubCredType" json:"subType,omitempty" yaml:"subType"`
}

func (m *K8SCreds) Reset()                    { *m = K8SCreds{} }
func (m *K8SCreds) String() string            { return proto.CompactTextString(m) }
func (*K8SCreds) ProtoMessage()               {}
func (*K8SCreds) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *K8SCreds) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *K8SCreds) GetK8SContents() string {
	if m != nil {
		return m.K8SContents
	}
	return ""
}

func (m *K8SCreds) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *K8SCreds) GetSubType() SubCredType {
	if m != nil {
		return m.SubType
	}
	return SubCredType_NIL_SCT
}

type K8SCredsWrapper struct {
	K8SCreds []*K8SCreds `protobuf:"bytes,2,rep,name=K8SCreds" json:"K8SCreds,omitempty"`
}

func (m *K8SCredsWrapper) Reset()                    { *m = K8SCredsWrapper{} }
func (m *K8SCredsWrapper) String() string            { return proto.CompactTextString(m) }
func (*K8SCredsWrapper) ProtoMessage()               {}
func (*K8SCredsWrapper) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *K8SCredsWrapper) GetK8SCreds() []*K8SCreds {
	if m != nil {
		return m.K8SCreds
	}
	return nil
}

type StatusQuery struct {
	// hash is the git hash to get status of
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	// acctName is the corresponding account that the hash is attached to
	AcctName string `protobuf:"bytes,2,opt,name=acctName" json:"acctName,omitempty"`
	// repoName is the corresponding repo name that the hash is attached to
	RepoName string `protobuf:"bytes,3,opt,name=repoName" json:"repoName,omitempty"`
	// partialRepo is just the first n letters of repo
	PartialRepo string `protobuf:"bytes,4,opt,name=partialRepo" json:"partialRepo,omitempty"`
}

func (m *StatusQuery) Reset()                    { *m = StatusQuery{} }
func (m *StatusQuery) String() string            { return proto.CompactTextString(m) }
func (*StatusQuery) ProtoMessage()               {}
func (*StatusQuery) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *StatusQuery) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *StatusQuery) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *StatusQuery) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *StatusQuery) GetPartialRepo() string {
	if m != nil {
		return m.PartialRepo
	}
	return ""
}

type BuildQuery struct {
	Hash    string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	BuildId int64  `protobuf:"varint,2,opt,name=buildId" json:"buildId,omitempty"`
}

func (m *BuildQuery) Reset()                    { *m = BuildQuery{} }
func (m *BuildQuery) String() string            { return proto.CompactTextString(m) }
func (*BuildQuery) ProtoMessage()               {}
func (*BuildQuery) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *BuildQuery) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BuildQuery) GetBuildId() int64 {
	if m != nil {
		return m.BuildId
	}
	return 0
}

type Builds struct {
	Builds map[string]*BuildRuntimeInfo `protobuf:"bytes,1,rep,name=builds" json:"builds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Builds) Reset()                    { *m = Builds{} }
func (m *Builds) String() string            { return proto.CompactTextString(m) }
func (*Builds) ProtoMessage()               {}
func (*Builds) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *Builds) GetBuilds() map[string]*BuildRuntimeInfo {
	if m != nil {
		return m.Builds
	}
	return nil
}

type BuildRuntimeInfo struct {
	Done     bool   `protobuf:"varint,1,opt,name=done" json:"done,omitempty"`
	Ip       string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	GrpcPort string `protobuf:"bytes,3,opt,name=grpcPort" json:"grpcPort,omitempty"`
	Hash     string `protobuf:"bytes,4,opt,name=hash" json:"hash,omitempty"`
	AcctName string `protobuf:"bytes,5,opt,name=acctName" json:"acctName,omitempty"`
	RepoName string `protobuf:"bytes,6,opt,name=repoName" json:"repoName,omitempty"`
	WsPort   string `protobuf:"bytes,7,opt,name=wsPort" json:"wsPort,omitempty"`
}

func (m *BuildRuntimeInfo) Reset()                    { *m = BuildRuntimeInfo{} }
func (m *BuildRuntimeInfo) String() string            { return proto.CompactTextString(m) }
func (*BuildRuntimeInfo) ProtoMessage()               {}
func (*BuildRuntimeInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *BuildRuntimeInfo) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *BuildRuntimeInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BuildRuntimeInfo) GetGrpcPort() string {
	if m != nil {
		return m.GrpcPort
	}
	return ""
}

func (m *BuildRuntimeInfo) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BuildRuntimeInfo) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *BuildRuntimeInfo) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *BuildRuntimeInfo) GetWsPort() string {
	if m != nil {
		return m.WsPort
	}
	return ""
}

type LineResponse struct {
	OutputLine string `protobuf:"bytes,1,opt,name=outputLine" json:"outputLine,omitempty"`
}

func (m *LineResponse) Reset()                    { *m = LineResponse{} }
func (m *LineResponse) String() string            { return proto.CompactTextString(m) }
func (*LineResponse) ProtoMessage()               {}
func (*LineResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *LineResponse) GetOutputLine() string {
	if m != nil {
		return m.OutputLine
	}
	return ""
}

type RepoAccount struct {
	Repo    string `protobuf:"bytes,1,opt,name=repo" json:"repo,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Limit   int32  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (m *RepoAccount) Reset()                    { *m = RepoAccount{} }
func (m *RepoAccount) String() string            { return proto.CompactTextString(m) }
func (*RepoAccount) ProtoMessage()               {}
func (*RepoAccount) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *RepoAccount) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *RepoAccount) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RepoAccount) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Status struct {
	BuildSum   *BuildSummary  `protobuf:"bytes,1,opt,name=buildSum" json:"buildSum,omitempty"`
	Stages     []*StageStatus `protobuf:"bytes,2,rep,name=stages" json:"stages,omitempty"`
	IsInConsul bool           `protobuf:"varint,3,opt,name=isInConsul" json:"isInConsul,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *Status) GetBuildSum() *BuildSummary {
	if m != nil {
		return m.BuildSum
	}
	return nil
}

func (m *Status) GetStages() []*StageStatus {
	if m != nil {
		return m.Stages
	}
	return nil
}

func (m *Status) GetIsInConsul() bool {
	if m != nil {
		return m.IsInConsul
	}
	return false
}

type StageStatus struct {
	StageStatus   string                      `protobuf:"bytes,1,opt,name=StageStatus" json:"StageStatus,omitempty"`
	Error         string                      `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Status        int32                       `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	Messages      []string                    `protobuf:"bytes,4,rep,name=messages" json:"messages,omitempty"`
	StartTime     *google_protobuf2.Timestamp `protobuf:"bytes,5,opt,name=startTime" json:"startTime,omitempty"`
	StageDuration float64                     `protobuf:"fixed64,6,opt,name=stageDuration" json:"stageDuration,omitempty"`
}

func (m *StageStatus) Reset()                    { *m = StageStatus{} }
func (m *StageStatus) String() string            { return proto.CompactTextString(m) }
func (*StageStatus) ProtoMessage()               {}
func (*StageStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *StageStatus) GetStageStatus() string {
	if m != nil {
		return m.StageStatus
	}
	return ""
}

func (m *StageStatus) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *StageStatus) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *StageStatus) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *StageStatus) GetStartTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *StageStatus) GetStageDuration() float64 {
	if m != nil {
		return m.StageDuration
	}
	return 0
}

type BuildSummary struct {
	Hash          string                      `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	Failed        bool                        `protobuf:"varint,2,opt,name=failed" json:"failed,omitempty"`
	BuildTime     *google_protobuf2.Timestamp `protobuf:"bytes,3,opt,name=buildTime" json:"buildTime,omitempty"`
	Account       string                      `protobuf:"bytes,4,opt,name=account" json:"account,omitempty"`
	BuildDuration float64                     `protobuf:"fixed64,5,opt,name=buildDuration" json:"buildDuration,omitempty"`
	Repo          string                      `protobuf:"bytes,6,opt,name=repo" json:"repo,omitempty"`
	Branch        string                      `protobuf:"bytes,7,opt,name=branch" json:"branch,omitempty"`
	BuildId       int64                       `protobuf:"varint,8,opt,name=buildId" json:"buildId,omitempty"`
	QueueTime     *google_protobuf2.Timestamp `protobuf:"bytes,9,opt,name=queueTime" json:"queueTime,omitempty"`
}

func (m *BuildSummary) Reset()                    { *m = BuildSummary{} }
func (m *BuildSummary) String() string            { return proto.CompactTextString(m) }
func (*BuildSummary) ProtoMessage()               {}
func (*BuildSummary) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *BuildSummary) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BuildSummary) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

func (m *BuildSummary) GetBuildTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.BuildTime
	}
	return nil
}

func (m *BuildSummary) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *BuildSummary) GetBuildDuration() float64 {
	if m != nil {
		return m.BuildDuration
	}
	return 0
}

func (m *BuildSummary) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *BuildSummary) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *BuildSummary) GetBuildId() int64 {
	if m != nil {
		return m.BuildId
	}
	return 0
}

func (m *BuildSummary) GetQueueTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.QueueTime
	}
	return nil
}

type Summaries struct {
	Sums []*BuildSummary `protobuf:"bytes,1,rep,name=sums" json:"sums,omitempty"`
}

func (m *Summaries) Reset()                    { *m = Summaries{} }
func (m *Summaries) String() string            { return proto.CompactTextString(m) }
func (*Summaries) ProtoMessage()               {}
func (*Summaries) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *Summaries) GetSums() []*BuildSummary {
	if m != nil {
		return m.Sums
	}
	return nil
}

type PollRequest struct {
	Account      string                      `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Repo         string                      `protobuf:"bytes,2,opt,name=repo" json:"repo,omitempty"`
	Cron         string                      `protobuf:"bytes,4,opt,name=cron" json:"cron,omitempty"`
	Branches     string                      `protobuf:"bytes,5,opt,name=branches" json:"branches,omitempty"`
	LastCronTime *google_protobuf2.Timestamp `protobuf:"bytes,6,opt,name=lastCronTime" json:"lastCronTime,omitempty"`
	LastHashes   map[string]string           `protobuf:"bytes,7,rep,name=lastHashes" json:"lastHashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *PollRequest) Reset()                    { *m = PollRequest{} }
func (m *PollRequest) String() string            { return proto.CompactTextString(m) }
func (*PollRequest) ProtoMessage()               {}
func (*PollRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *PollRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *PollRequest) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *PollRequest) GetCron() string {
	if m != nil {
		return m.Cron
	}
	return ""
}

func (m *PollRequest) GetBranches() string {
	if m != nil {
		return m.Branches
	}
	return ""
}

func (m *PollRequest) GetLastCronTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.LastCronTime
	}
	return nil
}

func (m *PollRequest) GetLastHashes() map[string]string {
	if m != nil {
		return m.LastHashes
	}
	return nil
}

type Polls struct {
	Polls []*PollRequest `protobuf:"bytes,1,rep,name=polls" json:"polls,omitempty"`
}

func (m *Polls) Reset()                    { *m = Polls{} }
func (m *Polls) String() string            { return proto.CompactTextString(m) }
func (*Polls) ProtoMessage()               {}
func (*Polls) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *Polls) GetPolls() []*PollRequest {
	if m != nil {
		return m.Polls
	}
	return nil
}

type Exists struct {
	Exists bool `protobuf:"varint,1,opt,name=exists" json:"exists,omitempty"`
}

func (m *Exists) Reset()                    { *m = Exists{} }
func (m *Exists) String() string            { return proto.CompactTextString(m) }
func (*Exists) ProtoMessage()               {}
func (*Exists) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

func (m *Exists) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func init() {
	proto.RegisterType((*BuildReq)(nil), "models.BuildReq")
	proto.RegisterType((*AllCredsWrapper)(nil), "models.AllCredsWrapper")
	proto.RegisterType((*CredWrapper)(nil), "models.CredWrapper")
	proto.RegisterType((*SSHKeyWrapper)(nil), "models.SSHKeyWrapper")
	proto.RegisterType((*VCSCreds)(nil), "models.VCSCreds")
	proto.RegisterType((*RepoCredWrapper)(nil), "models.RepoCredWrapper")
	proto.RegisterType((*RepoCreds)(nil), "models.RepoCreds")
	proto.RegisterType((*K8SCreds)(nil), "models.K8SCreds")
	proto.RegisterType((*K8SCredsWrapper)(nil), "models.K8SCredsWrapper")
	proto.RegisterType((*StatusQuery)(nil), "models.StatusQuery")
	proto.RegisterType((*BuildQuery)(nil), "models.BuildQuery")
	proto.RegisterType((*Builds)(nil), "models.Builds")
	proto.RegisterType((*BuildRuntimeInfo)(nil), "models.BuildRuntimeInfo")
	proto.RegisterType((*LineResponse)(nil), "models.LineResponse")
	proto.RegisterType((*RepoAccount)(nil), "models.RepoAccount")
	proto.RegisterType((*Status)(nil), "models.Status")
	proto.RegisterType((*StageStatus)(nil), "models.StageStatus")
	proto.RegisterType((*BuildSummary)(nil), "models.BuildSummary")
	proto.RegisterType((*Summaries)(nil), "models.Summaries")
	proto.RegisterType((*PollRequest)(nil), "models.PollRequest")
	proto.RegisterType((*Polls)(nil), "models.Polls")
	proto.RegisterType((*Exists)(nil), "models.Exists")
	proto.RegisterEnum("models.CredType", CredType_name, CredType_value)
	proto.RegisterEnum("models.SubCredType", SubCredType_name, SubCredType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GuideOcelot service

type GuideOcelotClient interface {
	GetVCSCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*CredWrapper, error)
	SetVCSCreds(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	UpdateVCSCreds(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	VCSCredExists(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*Exists, error)
	CheckConn(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	SetVCSPrivateKey(ctx context.Context, in *SSHKeyWrapper, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	UpdateRepoCreds(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	RepoCredExists(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*Exists, error)
	UpdateK8SCreds(ctx context.Context, in *K8SCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	K8SCredExists(ctx context.Context, in *K8SCreds, opts ...grpc.CallOption) (*Exists, error)
	GetRepoCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*RepoCredWrapper, error)
	SetRepoCreds(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	SetK8SCreds(ctx context.Context, in *K8SCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	GetK8SCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*K8SCredsWrapper, error)
	GetAllCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*AllCredsWrapper, error)
	BuildRuntime(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (*Builds, error)
	Logs(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (GuideOcelot_LogsClient, error)
	LastFewSummaries(ctx context.Context, in *RepoAccount, opts ...grpc.CallOption) (*Summaries, error)
	GetStatus(ctx context.Context, in *StatusQuery, opts ...grpc.CallOption) (*Status, error)
	WatchRepo(ctx context.Context, in *RepoAccount, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	BuildRepoAndHash(ctx context.Context, in *BuildReq, opts ...grpc.CallOption) (GuideOcelot_BuildRepoAndHashClient, error)
	PollRepo(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	DeletePollRepo(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	ListPolledRepos(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Polls, error)
	FindWerker(ctx context.Context, in *BuildReq, opts ...grpc.CallOption) (*BuildRuntimeInfo, error)
}

type guideOcelotClient struct {
	cc *grpc.ClientConn
}

func NewGuideOcelotClient(cc *grpc.ClientConn) GuideOcelotClient {
	return &guideOcelotClient{cc}
}

func (c *guideOcelotClient) GetVCSCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*CredWrapper, error) {
	out := new(CredWrapper)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetVCSCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) SetVCSCreds(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/SetVCSCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) UpdateVCSCreds(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/UpdateVCSCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) VCSCredExists(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*Exists, error) {
	out := new(Exists)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/VCSCredExists", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) CheckConn(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/CheckConn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) SetVCSPrivateKey(ctx context.Context, in *SSHKeyWrapper, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/SetVCSPrivateKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) UpdateRepoCreds(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/UpdateRepoCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) RepoCredExists(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*Exists, error) {
	out := new(Exists)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/RepoCredExists", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) UpdateK8SCreds(ctx context.Context, in *K8SCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/UpdateK8SCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) K8SCredExists(ctx context.Context, in *K8SCreds, opts ...grpc.CallOption) (*Exists, error) {
	out := new(Exists)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/K8SCredExists", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) GetRepoCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*RepoCredWrapper, error) {
	out := new(RepoCredWrapper)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetRepoCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) SetRepoCreds(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/SetRepoCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) SetK8SCreds(ctx context.Context, in *K8SCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/SetK8SCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) GetK8SCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*K8SCredsWrapper, error) {
	out := new(K8SCredsWrapper)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetK8SCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) GetAllCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*AllCredsWrapper, error) {
	out := new(AllCredsWrapper)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetAllCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) BuildRuntime(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (*Builds, error) {
	out := new(Builds)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/BuildRuntime", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) Logs(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (GuideOcelot_LogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GuideOcelot_serviceDesc.Streams[0], c.cc, "/models.GuideOcelot/Logs", opts...)
	if err != nil {
		return nil, err
	}
	x := &guideOcelotLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GuideOcelot_LogsClient interface {
	Recv() (*LineResponse, error)
	grpc.ClientStream
}

type guideOcelotLogsClient struct {
	grpc.ClientStream
}

func (x *guideOcelotLogsClient) Recv() (*LineResponse, error) {
	m := new(LineResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *guideOcelotClient) LastFewSummaries(ctx context.Context, in *RepoAccount, opts ...grpc.CallOption) (*Summaries, error) {
	out := new(Summaries)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/LastFewSummaries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) GetStatus(ctx context.Context, in *StatusQuery, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) WatchRepo(ctx context.Context, in *RepoAccount, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/WatchRepo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) BuildRepoAndHash(ctx context.Context, in *BuildReq, opts ...grpc.CallOption) (GuideOcelot_BuildRepoAndHashClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GuideOcelot_serviceDesc.Streams[1], c.cc, "/models.GuideOcelot/BuildRepoAndHash", opts...)
	if err != nil {
		return nil, err
	}
	x := &guideOcelotBuildRepoAndHashClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GuideOcelot_BuildRepoAndHashClient interface {
	Recv() (*LineResponse, error)
	grpc.ClientStream
}

type guideOcelotBuildRepoAndHashClient struct {
	grpc.ClientStream
}

func (x *guideOcelotBuildRepoAndHashClient) Recv() (*LineResponse, error) {
	m := new(LineResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *guideOcelotClient) PollRepo(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/PollRepo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) DeletePollRepo(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/DeletePollRepo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) ListPolledRepos(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Polls, error) {
	out := new(Polls)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/ListPolledRepos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) FindWerker(ctx context.Context, in *BuildReq, opts ...grpc.CallOption) (*BuildRuntimeInfo, error) {
	out := new(BuildRuntimeInfo)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/FindWerker", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GuideOcelot service

type GuideOcelotServer interface {
	GetVCSCreds(context.Context, *google_protobuf.Empty) (*CredWrapper, error)
	SetVCSCreds(context.Context, *VCSCreds) (*google_protobuf.Empty, error)
	UpdateVCSCreds(context.Context, *VCSCreds) (*google_protobuf.Empty, error)
	VCSCredExists(context.Context, *VCSCreds) (*Exists, error)
	CheckConn(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
	SetVCSPrivateKey(context.Context, *SSHKeyWrapper) (*google_protobuf.Empty, error)
	UpdateRepoCreds(context.Context, *RepoCreds) (*google_protobuf.Empty, error)
	RepoCredExists(context.Context, *RepoCreds) (*Exists, error)
	UpdateK8SCreds(context.Context, *K8SCreds) (*google_protobuf.Empty, error)
	K8SCredExists(context.Context, *K8SCreds) (*Exists, error)
	GetRepoCreds(context.Context, *google_protobuf.Empty) (*RepoCredWrapper, error)
	SetRepoCreds(context.Context, *RepoCreds) (*google_protobuf.Empty, error)
	SetK8SCreds(context.Context, *K8SCreds) (*google_protobuf.Empty, error)
	GetK8SCreds(context.Context, *google_protobuf.Empty) (*K8SCredsWrapper, error)
	GetAllCreds(context.Context, *google_protobuf.Empty) (*AllCredsWrapper, error)
	BuildRuntime(context.Context, *BuildQuery) (*Builds, error)
	Logs(*BuildQuery, GuideOcelot_LogsServer) error
	LastFewSummaries(context.Context, *RepoAccount) (*Summaries, error)
	GetStatus(context.Context, *StatusQuery) (*Status, error)
	WatchRepo(context.Context, *RepoAccount) (*google_protobuf.Empty, error)
	BuildRepoAndHash(*BuildReq, GuideOcelot_BuildRepoAndHashServer) error
	PollRepo(context.Context, *PollRequest) (*google_protobuf.Empty, error)
	DeletePollRepo(context.Context, *PollRequest) (*google_protobuf.Empty, error)
	ListPolledRepos(context.Context, *google_protobuf.Empty) (*Polls, error)
	FindWerker(context.Context, *BuildReq) (*BuildRuntimeInfo, error)
}

func RegisterGuideOcelotServer(s *grpc.Server, srv GuideOcelotServer) {
	s.RegisterService(&_GuideOcelot_serviceDesc, srv)
}

func _GuideOcelot_GetVCSCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetVCSCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetVCSCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetVCSCreds(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_SetVCSCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VCSCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).SetVCSCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/SetVCSCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).SetVCSCreds(ctx, req.(*VCSCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_UpdateVCSCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VCSCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).UpdateVCSCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/UpdateVCSCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).UpdateVCSCreds(ctx, req.(*VCSCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_VCSCredExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VCSCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).VCSCredExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/VCSCredExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).VCSCredExists(ctx, req.(*VCSCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_CheckConn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).CheckConn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/CheckConn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).CheckConn(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_SetVCSPrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHKeyWrapper)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).SetVCSPrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/SetVCSPrivateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).SetVCSPrivateKey(ctx, req.(*SSHKeyWrapper))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_UpdateRepoCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).UpdateRepoCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/UpdateRepoCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).UpdateRepoCreds(ctx, req.(*RepoCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_RepoCredExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).RepoCredExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/RepoCredExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).RepoCredExists(ctx, req.(*RepoCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_UpdateK8SCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).UpdateK8SCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/UpdateK8SCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).UpdateK8SCreds(ctx, req.(*K8SCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_K8SCredExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).K8SCredExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/K8SCredExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).K8SCredExists(ctx, req.(*K8SCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_GetRepoCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetRepoCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetRepoCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetRepoCreds(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_SetRepoCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).SetRepoCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/SetRepoCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).SetRepoCreds(ctx, req.(*RepoCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_SetK8SCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).SetK8SCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/SetK8SCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).SetK8SCreds(ctx, req.(*K8SCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_GetK8SCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetK8SCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetK8SCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetK8SCreds(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_GetAllCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetAllCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetAllCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetAllCreds(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_BuildRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).BuildRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/BuildRuntime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).BuildRuntime(ctx, req.(*BuildQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GuideOcelotServer).Logs(m, &guideOcelotLogsServer{stream})
}

type GuideOcelot_LogsServer interface {
	Send(*LineResponse) error
	grpc.ServerStream
}

type guideOcelotLogsServer struct {
	grpc.ServerStream
}

func (x *guideOcelotLogsServer) Send(m *LineResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GuideOcelot_LastFewSummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).LastFewSummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/LastFewSummaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).LastFewSummaries(ctx, req.(*RepoAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetStatus(ctx, req.(*StatusQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_WatchRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).WatchRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/WatchRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).WatchRepo(ctx, req.(*RepoAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_BuildRepoAndHash_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GuideOcelotServer).BuildRepoAndHash(m, &guideOcelotBuildRepoAndHashServer{stream})
}

type GuideOcelot_BuildRepoAndHashServer interface {
	Send(*LineResponse) error
	grpc.ServerStream
}

type guideOcelotBuildRepoAndHashServer struct {
	grpc.ServerStream
}

func (x *guideOcelotBuildRepoAndHashServer) Send(m *LineResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GuideOcelot_PollRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).PollRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/PollRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).PollRepo(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_DeletePollRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).DeletePollRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/DeletePollRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).DeletePollRepo(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_ListPolledRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).ListPolledRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/ListPolledRepos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).ListPolledRepos(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_FindWerker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).FindWerker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/FindWerker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).FindWerker(ctx, req.(*BuildReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GuideOcelot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.GuideOcelot",
	HandlerType: (*GuideOcelotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVCSCreds",
			Handler:    _GuideOcelot_GetVCSCreds_Handler,
		},
		{
			MethodName: "SetVCSCreds",
			Handler:    _GuideOcelot_SetVCSCreds_Handler,
		},
		{
			MethodName: "UpdateVCSCreds",
			Handler:    _GuideOcelot_UpdateVCSCreds_Handler,
		},
		{
			MethodName: "VCSCredExists",
			Handler:    _GuideOcelot_VCSCredExists_Handler,
		},
		{
			MethodName: "CheckConn",
			Handler:    _GuideOcelot_CheckConn_Handler,
		},
		{
			MethodName: "SetVCSPrivateKey",
			Handler:    _GuideOcelot_SetVCSPrivateKey_Handler,
		},
		{
			MethodName: "UpdateRepoCreds",
			Handler:    _GuideOcelot_UpdateRepoCreds_Handler,
		},
		{
			MethodName: "RepoCredExists",
			Handler:    _GuideOcelot_RepoCredExists_Handler,
		},
		{
			MethodName: "UpdateK8SCreds",
			Handler:    _GuideOcelot_UpdateK8SCreds_Handler,
		},
		{
			MethodName: "K8SCredExists",
			Handler:    _GuideOcelot_K8SCredExists_Handler,
		},
		{
			MethodName: "GetRepoCreds",
			Handler:    _GuideOcelot_GetRepoCreds_Handler,
		},
		{
			MethodName: "SetRepoCreds",
			Handler:    _GuideOcelot_SetRepoCreds_Handler,
		},
		{
			MethodName: "SetK8SCreds",
			Handler:    _GuideOcelot_SetK8SCreds_Handler,
		},
		{
			MethodName: "GetK8SCreds",
			Handler:    _GuideOcelot_GetK8SCreds_Handler,
		},
		{
			MethodName: "GetAllCreds",
			Handler:    _GuideOcelot_GetAllCreds_Handler,
		},
		{
			MethodName: "BuildRuntime",
			Handler:    _GuideOcelot_BuildRuntime_Handler,
		},
		{
			MethodName: "LastFewSummaries",
			Handler:    _GuideOcelot_LastFewSummaries_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _GuideOcelot_GetStatus_Handler,
		},
		{
			MethodName: "WatchRepo",
			Handler:    _GuideOcelot_WatchRepo_Handler,
		},
		{
			MethodName: "PollRepo",
			Handler:    _GuideOcelot_PollRepo_Handler,
		},
		{
			MethodName: "DeletePollRepo",
			Handler:    _GuideOcelot_DeletePollRepo_Handler,
		},
		{
			MethodName: "ListPolledRepos",
			Handler:    _GuideOcelot_ListPolledRepos_Handler,
		},
		{
			MethodName: "FindWerker",
			Handler:    _GuideOcelot_FindWerker_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _GuideOcelot_Logs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BuildRepoAndHash",
			Handler:       _GuideOcelot_BuildRepoAndHash_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "guideocelot.proto",
}

func init() { proto.RegisterFile("guideocelot.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 2730 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0xcf, 0x8f, 0x23, 0x47,
	0xf5, 0xdf, 0xb6, 0x67, 0x3c, 0x9e, 0xf2, 0xcc, 0xac, 0xb7, 0x77, 0xb3, 0xdf, 0x91, 0xf3, 0x15,
	0x94, 0x9a, 0x04, 0x2d, 0x9b, 0x59, 0xcf, 0xee, 0x24, 0x11, 0x93, 0x85, 0x04, 0xbc, 0xce, 0xec,
	0xec, 0x68, 0x26, 0xb3, 0xbb, 0xed, 0x99, 0x0d, 0xe2, 0x00, 0x69, 0xb7, 0xcb, 0x76, 0xc7, 0xed,
	0xee, 0xde, 0xaa, 0xea, 0x71, 0x0c, 0x9c, 0x22, 0x91, 0x9c, 0x40, 0xc2, 0x1c, 0x10, 0xe2, 0xc0,
	0x09, 0x71, 0x42, 0xb9, 0x44, 0x48, 0xdc, 0x91, 0x40, 0x5c, 0x23, 0x21, 0x71, 0xe1, 0xc4, 0x85,
	0x03, 0x08, 0xfe, 0x03, 0xf4, 0x5e, 0x55, 0xb5, 0xdb, 0x9e, 0x71, 0x36, 0xc9, 0xc9, 0x5d, 0xaf,
	0x5e, 0xbd, 0xfa, 0xbc, 0x9f, 0xf5, 0x9e, 0xc9, 0x95, 0x5e, 0x1a, 0x74, 0x58, 0xec, 0xb3, 0x30,
	0x96, 0xf5, 0x84, 0xc7, 0x32, 0xb6, 0x4b, 0xc3, 0xb8, 0xc3, 0x42, 0x51, 0x7b, 0xbe, 0x17, 0xc7,
	0xbd, 0x90, 0x6d, 0x23, 0xb5, 0x9d, 0x76, 0xb7, 0xd9, 0x30, 0x91, 0x63, 0xc5, 0x54, 0xfb, 0x7f,
	0xbd, 0xe9, 0x25, 0xc1, 0xb6, 0x17, 0x45, 0xb1, 0xf4, 0x64, 0x10, 0x47, 0x42, 0xef, 0x7e, 0x79,
	0xfe, 0xa8, 0x0c, 0x86, 0x4c, 0x48, 0x6f, 0x98, 0x68, 0x86, 0x2d, 0xfc, 0xf1, 0x6f, 0xf5, 0x58,
	0x74, 0x4b, 0x8c, 0xbc, 0x5e, 0x8f, 0xf1, 0xed, 0x38, 0x41, 0x11, 0xe7, 0xc5, 0x39, 0x2e, 0x29,
	0xdf, 0x4b, 0x83, 0xb0, 0xe3, 0xb2, 0xa7, 0x76, 0x8d, 0x94, 0x3d, 0xdf, 0x97, 0x2e, 0x4b, 0xe2,
	0x4d, 0x8b, 0x5a, 0x37, 0x56, 0xdd, 0x6c, 0x6d, 0xdb, 0x64, 0xa9, 0xef, 0x89, 0xfe, 0x66, 0x01,
	0xe9, 0xf8, 0x6d, 0x5f, 0x27, 0xa5, 0x36, 0xf7, 0x22, 0xbf, 0xbf, 0x59, 0x44, 0xaa, 0x5e, 0x39,
	0x63, 0x72, 0xb9, 0x11, 0x86, 0x4d, 0xce, 0x3a, 0xe2, 0x6d, 0xee, 0x25, 0x09, 0xe3, 0xf6, 0xab,
	0x64, 0x95, 0xb3, 0x24, 0x46, 0x1a, 0xca, 0xae, 0xec, 0xfc, 0x5f, 0x5d, 0x19, 0xa3, 0xee, 0xea,
	0x0d, 0xcd, 0xeb, 0x4e, 0x39, 0xed, 0x6d, 0x52, 0x3e, 0xf3, 0x85, 0x3a, 0x55, 0xc4, 0x53, 0x57,
	0xcd, 0xa9, 0xfc, 0x89, 0x8c, 0xc9, 0xb9, 0x43, 0x2a, 0xb9, 0x0d, 0xdb, 0x21, 0xc5, 0x33, 0x5f,
	0x6c, 0x16, 0x68, 0xf1, 0x46, 0x65, 0xa7, 0x6a, 0x8e, 0x3e, 0x69, 0xb6, 0x90, 0xdb, 0x85, 0x4d,
	0xe7, 0x07, 0x64, 0xbd, 0xd5, 0x7a, 0x70, 0xc8, 0xc6, 0xe6, 0x90, 0x36, 0xc3, 0xb1, 0x37, 0x64,
	0x79, 0x33, 0xc0, 0xda, 0xfe, 0x12, 0x21, 0x09, 0x0f, 0xce, 0x3c, 0xc9, 0x0e, 0xd9, 0x18, 0x8d,
	0xb1, 0xe6, 0xe6, 0x28, 0xf6, 0x2d, 0xb2, 0x22, 0xd2, 0xf6, 0xc9, 0x38, 0x61, 0x9b, 0x84, 0x5a,
	0x37, 0x36, 0xa6, 0x78, 0x5b, 0x69, 0x1b, 0x2e, 0x85, 0x2d, 0xd7, 0xf0, 0x38, 0xff, 0xb5, 0x48,
	0xd9, 0xa0, 0x81, 0x7b, 0xfd, 0x30, 0x60, 0x91, 0x3c, 0xe8, 0x98, 0x7b, 0xcd, 0xda, 0x76, 0xc8,
	0x9a, 0xfa, 0x6e, 0x31, 0x9f, 0x33, 0xa9, 0xdd, 0x30, 0x43, 0x03, 0x6c, 0x41, 0x87, 0x45, 0x32,
	0xe8, 0x06, 0x8c, 0x6f, 0x96, 0x91, 0x23, 0x47, 0x01, 0xf9, 0x32, 0x1e, 0xb0, 0xe8, 0xd4, 0x3d,
	0xd2, 0x0e, 0xcb, 0xd6, 0x33, 0x3a, 0x2f, 0x9d, 0xd7, 0x59, 0x88, 0xfe, 0xfd, 0x20, 0x64, 0x47,
	0xb1, 0xbf, 0x59, 0x52, 0x72, 0xa7, 0x94, 0xcf, 0xab, 0xf3, 0x2e, 0xb9, 0x3c, 0xe7, 0x71, 0xfb,
	0x45, 0xb2, 0x04, 0x3e, 0xdf, 0x2c, 0xa2, 0x9f, 0xae, 0xcc, 0x07, 0x86, 0x70, 0x71, 0xdb, 0xf9,
	0xb3, 0x45, 0x56, 0x33, 0x1a, 0x40, 0x4e, 0x05, 0xe3, 0x51, 0xce, 0x4d, 0x66, 0x0d, 0x7b, 0x89,
	0x27, 0xc4, 0x28, 0xe6, 0x1d, 0x6d, 0xaa, 0x6c, 0x6d, 0x6f, 0x92, 0x15, 0x90, 0x76, 0xca, 0x43,
	0xad, 0x8b, 0x59, 0x7e, 0x16, 0x03, 0x2e, 0x34, 0xd2, 0xe7, 0x34, 0xc2, 0x2f, 0x2c, 0x52, 0x3e,
	0xdc, 0x9d, 0x3a, 0x7e, 0x61, 0xc0, 0x51, 0x52, 0x19, 0xec, 0x8a, 0x66, 0x1c, 0x49, 0x16, 0x49,
	0xa1, 0x95, 0xc9, 0x93, 0xe6, 0x50, 0x17, 0xcf, 0xa1, 0xce, 0x21, 0x5b, 0xfe, 0x0c, 0xc8, 0xbe,
	0x45, 0x2e, 0x1b, 0x60, 0xc6, 0x3d, 0x5b, 0x53, 0xac, 0xf3, 0xa9, 0x64, 0xe8, 0x6e, 0xc6, 0xe1,
	0xfc, 0x90, 0x54, 0x5a, 0xd2, 0x93, 0xa9, 0x78, 0x9c, 0x32, 0x3e, 0xce, 0x0a, 0x87, 0x95, 0x2b,
	0x1c, 0x79, 0x85, 0x0b, 0x73, 0x0a, 0xd7, 0x48, 0x19, 0xfc, 0x81, 0x7b, 0x3a, 0x4a, 0xcd, 0x1a,
	0x8c, 0x91, 0x78, 0x5c, 0x06, 0x5e, 0x88, 0x35, 0x4a, 0xf9, 0x20, 0x4f, 0x72, 0xee, 0x12, 0x82,
	0xe5, 0x6c, 0xf1, 0xdd, 0x9b, 0x64, 0xa5, 0x0d, 0x1c, 0x07, 0x2a, 0x32, 0x8a, 0xae, 0x59, 0x3a,
	0x3f, 0xb3, 0x48, 0x09, 0x0f, 0x0b, 0x7b, 0x87, 0x94, 0x90, 0x0a, 0xb5, 0x0a, 0xf4, 0xad, 0x19,
	0x7d, 0xd5, 0xbe, 0xfe, 0xd9, 0x8b, 0x24, 0x1f, 0xbb, 0x9a, 0xb3, 0xd6, 0x22, 0x95, 0x1c, 0xd9,
	0xae, 0x92, 0xe2, 0x80, 0x8d, 0xf5, 0xd5, 0xf0, 0x69, 0xd7, 0xc9, 0xf2, 0x99, 0x17, 0xa6, 0x4a,
	0xe5, 0xca, 0xce, 0xe6, 0x8c, 0x4c, 0x37, 0x8d, 0xa0, 0x90, 0x1f, 0x44, 0xdd, 0xd8, 0x55, 0x6c,
	0x77, 0x0b, 0xbb, 0x96, 0xf3, 0x7b, 0x8b, 0x54, 0xe7, 0xf7, 0x41, 0xad, 0x4e, 0x1c, 0xa9, 0x58,
	0x29, 0xbb, 0xf8, 0x6d, 0x6f, 0x90, 0x42, 0x90, 0x68, 0x63, 0x16, 0x82, 0x04, 0xcc, 0xd8, 0xe3,
	0x89, 0xff, 0x28, 0xe6, 0xd2, 0x98, 0xd1, 0xac, 0x33, 0xb3, 0x2c, 0x2d, 0x70, 0xc9, 0xf2, 0xa7,
	0xb8, 0xa4, 0x34, 0xe7, 0x92, 0xeb, 0xa4, 0x34, 0x12, 0x78, 0xcb, 0x8a, 0x7a, 0x03, 0xd4, 0xca,
	0xa9, 0x93, 0xb5, 0xa3, 0x20, 0x62, 0x2e, 0x13, 0x49, 0x1c, 0x09, 0x2c, 0x22, 0x71, 0x2a, 0x93,
	0x54, 0x02, 0x55, 0x5b, 0x25, 0x47, 0x71, 0x1e, 0x93, 0x0a, 0x38, 0xb0, 0xe1, 0xfb, 0x71, 0x1a,
	0x21, 0x44, 0x3e, 0x7d, 0x86, 0xf0, 0x1b, 0x3c, 0xe7, 0xa9, 0x6d, 0xad, 0xa7, 0x59, 0xda, 0xd7,
	0xc8, 0x72, 0x18, 0x0c, 0x03, 0xa5, 0xe9, 0xb2, 0xab, 0x16, 0xce, 0x87, 0x16, 0x29, 0xa9, 0x48,
	0xb4, 0x6f, 0x93, 0x32, 0x7a, 0xa9, 0x95, 0x0e, 0xf5, 0xeb, 0x73, 0x6d, 0xc6, 0xfa, 0xad, 0x74,
	0x38, 0xf4, 0xf8, 0xd8, 0xcd, 0xb8, 0xec, 0x97, 0x48, 0x49, 0x48, 0xaf, 0xc7, 0x4c, 0xc4, 0x4f,
	0x93, 0x06, 0xa8, 0x4a, 0xac, 0xab, 0x59, 0x30, 0x05, 0xc5, 0x41, 0xd4, 0x8c, 0x23, 0x91, 0x86,
	0x08, 0xa2, 0xec, 0xe6, 0x28, 0xce, 0xdf, 0x2c, 0xcc, 0x09, 0x73, 0x0e, 0xe2, 0x38, 0xb7, 0xd4,
	0x4a, 0xce, 0x70, 0x5c, 0x23, 0xcb, 0x8c, 0xf3, 0x98, 0x6b, 0x4d, 0xd5, 0x02, 0x8c, 0x2d, 0xd4,
	0x11, 0xa5, 0xa8, 0x5e, 0x81, 0x83, 0x86, 0x4c, 0x08, 0x84, 0xbb, 0x44, 0x8b, 0xe0, 0x20, 0xb3,
	0xb6, 0x77, 0xc9, 0xaa, 0x90, 0x1e, 0x97, 0x27, 0x81, 0xf6, 0x2c, 0x44, 0xb3, 0xea, 0x21, 0xea,
	0xa6, 0x87, 0xa8, 0x9f, 0x98, 0x1e, 0xc2, 0x9d, 0x32, 0xdb, 0x2f, 0x90, 0x75, 0xd4, 0xef, 0xcd,
	0x94, 0x63, 0xcb, 0x80, 0xbe, 0xb7, 0xdc, 0x59, 0xa2, 0xf3, 0x71, 0x81, 0xac, 0xe5, 0x6d, 0x78,
	0x61, 0xd2, 0x5d, 0x27, 0xa5, 0xae, 0x17, 0x84, 0x4c, 0xe5, 0x5c, 0xd9, 0xd5, 0x2b, 0x00, 0x87,
	0x16, 0x47, 0x70, 0xc5, 0x67, 0x83, 0xcb, 0x98, 0xf3, 0xc1, 0xb0, 0x34, 0x1b, 0x0c, 0x2f, 0x90,
	0x75, 0x64, 0xcb, 0x60, 0x2f, 0x2b, 0xd8, 0x33, 0xc4, 0x2c, 0xc0, 0x4a, 0xb9, 0x00, 0x9b, 0xf6,
	0x33, 0x2b, 0xf9, 0x7e, 0x26, 0x5f, 0x32, 0xca, 0x33, 0x25, 0x03, 0xf0, 0x3f, 0x4d, 0x59, 0xca,
	0x10, 0xff, 0xea, 0xb3, 0xf1, 0x67, 0xcc, 0xce, 0xab, 0x64, 0x55, 0x19, 0x2c, 0x60, 0xc2, 0xbe,
	0x41, 0x96, 0x44, 0x3a, 0x34, 0xc5, 0xe6, 0xe2, 0xd0, 0x44, 0x0e, 0xe7, 0xa3, 0x02, 0xa9, 0x3c,
	0x8a, 0xc3, 0xd0, 0x65, 0x4f, 0x53, 0x26, 0x64, 0xde, 0x0c, 0xd6, 0xac, 0x19, 0x8c, 0x82, 0x85,
	0x9c, 0x82, 0x36, 0x59, 0xf2, 0x79, 0x1c, 0x99, 0xc4, 0x87, 0x6f, 0x88, 0x1d, 0xa5, 0x26, 0x13,
	0x26, 0xf1, 0xcd, 0xda, 0x7e, 0x83, 0xac, 0x85, 0x9e, 0x90, 0x4d, 0x1e, 0x47, 0xa8, 0x61, 0xe9,
	0x99, 0x1a, 0xce, 0xf0, 0xdb, 0x4d, 0x42, 0x60, 0xfd, 0xc0, 0x13, 0x20, 0x7d, 0x05, 0xb5, 0xfb,
	0x8a, 0xd1, 0x2e, 0xa7, 0x46, 0xfd, 0x28, 0xe3, 0x52, 0x35, 0x35, 0x77, 0xac, 0xf6, 0x3a, 0xb9,
	0x3c, 0xb7, 0x7d, 0x41, 0x6d, 0xbd, 0x96, 0xaf, 0xad, 0xab, 0xf9, 0x0a, 0xba, 0x43, 0x96, 0xe1,
	0x26, 0x61, 0x7f, 0x8d, 0x2c, 0x27, 0xf0, 0xa1, 0xad, 0x7c, 0xf5, 0x02, 0x1c, 0xae, 0xe2, 0x70,
	0x28, 0x29, 0xed, 0xbd, 0x17, 0x08, 0x29, 0x20, 0x24, 0x18, 0x7e, 0xe9, 0x62, 0xab, 0x57, 0x37,
	0x77, 0x48, 0xd9, 0x3c, 0x9d, 0x36, 0x21, 0xa5, 0xe3, 0x83, 0xa3, 0xef, 0x37, 0x4f, 0xaa, 0x97,
	0xec, 0x15, 0x52, 0x7c, 0xd2, 0x6c, 0x55, 0x2d, 0xbb, 0x4c, 0x96, 0xdc, 0xbd, 0x47, 0x0f, 0xab,
	0x05, 0x20, 0x1d, 0xee, 0xb6, 0xaa, 0xc5, 0x9b, 0x8c, 0x54, 0x72, 0x2f, 0xae, 0x5d, 0x21, 0x2b,
	0x70, 0xac, 0x85, 0xe7, 0xd6, 0xc9, 0xea, 0xbd, 0x83, 0x93, 0x7b, 0xa7, 0xcd, 0xc3, 0xbd, 0x93,
	0xaa, 0x05, 0x22, 0xf7, 0x0f, 0x4e, 0x1e, 0x9c, 0xde, 0xab, 0x16, 0xec, 0x55, 0xb2, 0x7c, 0xbc,
	0xf7, 0x9d, 0xd3, 0x56, 0xb5, 0x08, 0x9f, 0x6f, 0x35, 0x9e, 0xec, 0x1d, 0x57, 0x97, 0x80, 0xe3,
	0xcd, 0x87, 0xcd, 0xc3, 0x3d, 0xb7, 0xba, 0x6c, 0xaf, 0x91, 0xf2, 0xe1, 0xe9, 0xbd, 0xbd, 0xe6,
	0xc3, 0xe3, 0xfb, 0xd5, 0xd2, 0xce, 0xc7, 0xcf, 0x93, 0xca, 0x3e, 0x4c, 0x1e, 0x0f, 0x71, 0xf2,
	0xb0, 0x7f, 0x6b, 0x91, 0xca, 0x3e, 0x93, 0x59, 0x9b, 0x79, 0xfd, 0x9c, 0xfb, 0xf6, 0x60, 0xf8,
	0xa8, 0x5d, 0xd4, 0x59, 0x3b, 0x83, 0x49, 0xa3, 0x55, 0x7b, 0xec, 0x32, 0x99, 0xf2, 0x48, 0x50,
	0x2f, 0x0c, 0xe9, 0x93, 0x66, 0x8b, 0xfa, 0x20, 0x88, 0xca, 0xbe, 0x27, 0xa9, 0x1a, 0x6f, 0x68,
	0xdf, 0x13, 0xd4, 0x8b, 0x3a, 0xd4, 0xf7, 0x22, 0x9a, 0x0a, 0x46, 0xbb, 0x31, 0xa7, 0x7e, 0x9f,
	0xf9, 0x83, 0x20, 0xea, 0xd1, 0x38, 0x95, 0xd4, 0x8f, 0x3b, 0x8c, 0xca, 0x98, 0x62, 0xe6, 0xd4,
	0xdf, 0xff, 0xe4, 0x1f, 0x3f, 0x2f, 0x5c, 0xb6, 0xd7, 0xb7, 0xcf, 0xee, 0x6c, 0xa3, 0xb0, 0xed,
	0x33, 0x5f, 0xd8, 0xbf, 0x84, 0x32, 0x99, 0x43, 0x7a, 0xae, 0x61, 0xaf, 0x2d, 0xc0, 0xee, 0xbc,
	0x33, 0x69, 0xec, 0xd5, 0x9a, 0x8d, 0x4e, 0x87, 0x7a, 0x34, 0x62, 0xa3, 0x0c, 0x24, 0x34, 0x41,
	0x5e, 0x48, 0xfd, 0x38, 0xea, 0x06, 0x3d, 0x9d, 0xfa, 0x80, 0x42, 0xa3, 0x46, 0x94, 0x00, 0x0c,
	0xa1, 0xc6, 0xa9, 0x54, 0xc0, 0x6c, 0x67, 0x16, 0xd8, 0x5d, 0xeb, 0xa6, 0xfd, 0x4d, 0xb2, 0x71,
	0x9a, 0x74, 0x3c, 0xc9, 0xbe, 0x00, 0xba, 0x4b, 0xf6, 0xcb, 0x64, 0x5d, 0x73, 0xe9, 0xb8, 0x3a,
	0x7f, 0x78, 0xc3, 0x50, 0x14, 0x87, 0x73, 0xc9, 0x7e, 0x9d, 0xac, 0x36, 0x01, 0x57, 0x33, 0x8e,
	0xa2, 0x85, 0x5e, 0x5b, 0x7c, 0xe7, 0x3f, 0x2d, 0x52, 0x55, 0xd6, 0x7c, 0x34, 0x9d, 0x4f, 0x9e,
	0xcb, 0x9e, 0xb1, 0xfc, 0xc8, 0xb3, 0x50, 0xca, 0x6f, 0xac, 0x49, 0xe3, 0xc7, 0x56, 0xed, 0x7d,
	0xab, 0x21, 0xa5, 0xe7, 0xf7, 0xa9, 0xec, 0x33, 0x30, 0x26, 0x36, 0x9e, 0x34, 0xee, 0x52, 0x2f,
	0xa2, 0x42, 0xf4, 0x69, 0x37, 0x08, 0xd1, 0xb9, 0x1e, 0x3d, 0xf3, 0x05, 0xd5, 0x15, 0xa8, 0x4e,
	0x4f, 0xfa, 0x81, 0x50, 0x7b, 0xa3, 0x20, 0x0c, 0x69, 0x9b, 0x51, 0x0f, 0xc5, 0xb0, 0x0e, 0x30,
	0x83, 0x2c, 0x8c, 0x06, 0x94, 0xe8, 0x05, 0x11, 0xe3, 0xca, 0x21, 0x61, 0x1c, 0x41, 0xd4, 0xc0,
	0x3e, 0x54, 0x2d, 0x11, 0xc8, 0x98, 0x8f, 0x95, 0x67, 0xae, 0x3b, 0x57, 0x66, 0x3c, 0xb3, 0x2d,
	0x44, 0x1f, 0xbc, 0xf3, 0x06, 0xb9, 0xac, 0xbc, 0x33, 0x1d, 0x0f, 0xce, 0x4f, 0x11, 0x9f, 0x62,
	0xab, 0x57, 0xc9, 0x86, 0x61, 0xd3, 0x0e, 0xba, 0xe0, 0xf8, 0x79, 0x0f, 0x65, 0x41, 0x91, 0xb5,
	0xf2, 0xe7, 0x1a, 0xe3, 0x4f, 0x0f, 0x0a, 0xcd, 0x35, 0x1f, 0x14, 0xd9, 0xe1, 0xf3, 0x57, 0x7e,
	0x68, 0x91, 0xb5, 0x7d, 0x26, 0xa7, 0x7a, 0x2e, 0x0a, 0x8c, 0x45, 0xe3, 0xb5, 0x73, 0x7f, 0xd2,
	0xb8, 0x55, 0x7b, 0x69, 0x9f, 0x49, 0x4c, 0xe7, 0x41, 0x14, 0x8f, 0x22, 0xb4, 0x33, 0x0d, 0x22,
	0xc9, 0x7a, 0x3a, 0x47, 0xa6, 0xc9, 0x23, 0x94, 0xe5, 0xab, 0xf6, 0xc6, 0xd4, 0xf2, 0xf8, 0x98,
	0xfc, 0xc5, 0x22, 0x6b, 0xad, 0x3c, 0x92, 0xcf, 0x61, 0xf1, 0x9f, 0x5a, 0x93, 0x06, 0xaf, 0x25,
	0x90, 0xb0, 0x90, 0xae, 0x78, 0xfd, 0xf4, 0xca, 0x3a, 0x35, 0xc3, 0xda, 0x16, 0xd5, 0xb3, 0xd9,
	0x16, 0x35, 0xdd, 0xe8, 0x16, 0x35, 0x53, 0x1e, 0x16, 0x1c, 0x39, 0x4e, 0x18, 0xf5, 0x38, 0x84,
	0xca, 0xd3, 0x34, 0xe0, 0xac, 0x53, 0x57, 0xa4, 0x61, 0x2a, 0x24, 0x44, 0x5c, 0xc4, 0xde, 0x4b,
	0xc5, 0x8f, 0x3a, 0xb1, 0x3f, 0x60, 0x5c, 0x69, 0x72, 0xd5, 0x99, 0xd3, 0x04, 0x02, 0xe8, 0x31,
	0x56, 0x9e, 0x2f, 0xe0, 0xc6, 0xcd, 0xf3, 0x15, 0x63, 0xb0, 0x8b, 0x15, 0xe3, 0x14, 0xcb, 0x6e,
	0x26, 0xf2, 0x99, 0x7e, 0x9a, 0x9b, 0xba, 0x9c, 0xe7, 0xce, 0x17, 0xc9, 0xc1, 0xae, 0x00, 0xa4,
	0xfb, 0x4c, 0x9a, 0xff, 0x57, 0x9e, 0x2d, 0x76, 0xee, 0x9f, 0x18, 0xe7, 0x0a, 0x8a, 0xad, 0xd8,
	0xab, 0x99, 0x58, 0xfb, 0x48, 0x77, 0x70, 0x7a, 0xc6, 0xb0, 0xed, 0x99, 0x06, 0x04, 0x47, 0xa9,
	0x69, 0x24, 0xaa, 0x19, 0xc7, 0xe8, 0x6d, 0x57, 0x41, 0x0c, 0xa6, 0x31, 0xd7, 0xa7, 0x5f, 0x21,
	0x4b, 0x47, 0x71, 0x4f, 0x5c, 0x28, 0x25, 0x6b, 0x6d, 0xf2, 0xb3, 0x81, 0x73, 0xe9, 0xb6, 0x65,
	0xff, 0xaa, 0x40, 0xaa, 0xf0, 0xcc, 0xdf, 0x67, 0xa3, 0x69, 0x5f, 0x74, 0x35, 0x1f, 0x51, 0x7a,
	0x34, 0xa8, 0x5d, 0x99, 0x8e, 0xaf, 0x9a, 0xcf, 0xf9, 0xbb, 0x35, 0x69, 0xfc, 0xc9, 0xaa, 0xfd,
	0xd1, 0xc2, 0x3a, 0xc3, 0xf1, 0xb5, 0xa2, 0xc2, 0x6c, 0x43, 0xa1, 0xca, 0x8a, 0x8d, 0xc0, 0x1a,
	0xa3, 0xea, 0x18, 0xe7, 0x88, 0xa0, 0x03, 0xd5, 0x06, 0x02, 0x61, 0x3b, 0xab, 0x5c, 0x41, 0x57,
	0xc5, 0xe4, 0x57, 0x4d, 0x31, 0xc3, 0x10, 0xc3, 0x3f, 0xe9, 0xb6, 0xe0, 0x70, 0x44, 0x03, 0x49,
	0x17, 0x5e, 0x06, 0x79, 0xa5, 0xcf, 0x89, 0x3a, 0xc5, 0x61, 0x44, 0x31, 0x0b, 0x26, 0x69, 0x3f,
	0x1e, 0xd1, 0xa1, 0x17, 0x8d, 0x29, 0x8b, 0x24, 0x1e, 0x30, 0xb5, 0x51, 0x49, 0x62, 0x1d, 0x34,
	0xec, 0xba, 0x5d, 0x01, 0xc3, 0x0a, 0xdd, 0x53, 0xff, 0xa1, 0x48, 0x56, 0xf7, 0x99, 0xd4, 0xc3,
	0x41, 0x7e, 0x16, 0x31, 0x73, 0xf6, 0xd4, 0x41, 0x8a, 0xe8, 0x7c, 0x50, 0x9c, 0x34, 0xfe, 0x53,
	0xa8, 0xfd, 0xab, 0x90, 0x9d, 0x9b, 0x01, 0x0c, 0x16, 0x50, 0xd3, 0x03, 0x22, 0xa6, 0x22, 0x61,
	0x7e, 0xd0, 0x0d, 0x7c, 0xfd, 0x40, 0xd3, 0x07, 0x01, 0xe3, 0x1e, 0xf7, 0xfb, 0x63, 0xb4, 0xd7,
	0x80, 0x8d, 0xa1, 0x64, 0x87, 0x71, 0x3c, 0x48, 0x13, 0x3a, 0x0a, 0x64, 0xff, 0x2e, 0xd8, 0x08,
	0x7a, 0x7b, 0x2a, 0xd2, 0x24, 0x09, 0x03, 0xd6, 0xd9, 0x52, 0xf2, 0xe3, 0x28, 0x1c, 0x53, 0xc1,
	0xe0, 0x2c, 0x6d, 0x8f, 0x91, 0xa5, 0x4e, 0x0f, 0xba, 0x59, 0xfe, 0x62, 0xd6, 0x9a, 0xf1, 0x11,
	0xcd, 0x6a, 0x04, 0xe0, 0x4e, 0xa4, 0x9a, 0x89, 0xfe, 0x16, 0x25, 0xc6, 0x6a, 0x6d, 0x06, 0x29,
	0xdf, 0xa1, 0xd0, 0x62, 0x20, 0x12, 0x40, 0x04, 0x50, 0xc0, 0x6f, 0x69, 0xa2, 0xd5, 0xc0, 0x4b,
	0xf0, 0xf2, 0xdc, 0xff, 0x01, 0x34, 0x10, 0xb4, 0x17, 0x9c, 0x81, 0xbf, 0x22, 0xfd, 0xa0, 0x60,
	0xa3, 0xb7, 0x65, 0x3a, 0x00, 0xbc, 0xc0, 0x93, 0x12, 0x5c, 0x0b, 0x1a, 0x76, 0x83, 0x08, 0x7a,
	0x88, 0xa1, 0x27, 0xfd, 0xbe, 0x46, 0x9a, 0x99, 0x2b, 0xf4, 0x24, 0x83, 0xa2, 0x82, 0x6f, 0x16,
	0x0e, 0x41, 0xb4, 0xc3, 0xa4, 0x17, 0x84, 0x26, 0xa6, 0x3c, 0xdd, 0x3f, 0xac, 0xd9, 0x04, 0x9d,
	0xa7, 0xbc, 0xf5, 0x6b, 0x8b, 0xac, 0xbe, 0x0d, 0xf2, 0xf0, 0x7f, 0xd4, 0x0b, 0x43, 0x7a, 0x51,
	0x71, 0x61, 0x93, 0xc6, 0x71, 0xed, 0x68, 0x84, 0x60, 0xb2, 0x00, 0x4a, 0x13, 0xea, 0xd1, 0x11,
	0x6b, 0xf7, 0xe3, 0x78, 0x90, 0x05, 0xb3, 0x52, 0x72, 0x36, 0x88, 0x21, 0x0c, 0xbb, 0x01, 0x83,
	0x98, 0xcf, 0x8a, 0x23, 0xe2, 0xdb, 0x70, 0x30, 0xf9, 0x51, 0x2e, 0x54, 0xaa, 0xdf, 0x15, 0xcc,
	0x9f, 0x0c, 0x80, 0x29, 0xea, 0x40, 0xab, 0x3d, 0x2d, 0x81, 0xe6, 0xef, 0xe1, 0x05, 0xc9, 0xfb,
	0x6f, 0x6b, 0xd2, 0xf8, 0xab, 0x55, 0xfb, 0xc4, 0x52, 0x76, 0x99, 0x37, 0xa8, 0xe4, 0x41, 0xaf,
	0xc7, 0x38, 0xf5, 0x4c, 0x60, 0x1d, 0x74, 0x35, 0x60, 0xe5, 0x67, 0xd5, 0x39, 0x86, 0x9c, 0x79,
	0x9d, 0x31, 0x6d, 0x33, 0x16, 0x21, 0x1f, 0x94, 0xee, 0x6e, 0xcc, 0xd9, 0x16, 0xe4, 0x19, 0xf4,
	0x94, 0x6d, 0x66, 0x24, 0xb1, 0x0e, 0xc6, 0x1f, 0x7d, 0x17, 0x0a, 0xbc, 0xf9, 0x7b, 0x1a, 0x5d,
	0x85, 0xe2, 0x94, 0xc2, 0x78, 0x8d, 0xba, 0x01, 0x23, 0xea, 0x02, 0xc1, 0x58, 0x11, 0x70, 0xd0,
	0xa1, 0xdd, 0xd0, 0xeb, 0x41, 0xa4, 0x18, 0x2b, 0x41, 0xa4, 0x8d, 0x58, 0x18, 0xce, 0x58, 0x0b,
	0xe1, 0xdf, 0xb5, 0x6e, 0xde, 0xb6, 0xec, 0x8f, 0x2c, 0x52, 0x56, 0x53, 0x43, 0xde, 0xa1, 0xb9,
	0x39, 0x62, 0xa1, 0x43, 0xcf, 0x26, 0x8d, 0x77, 0x6a, 0xdf, 0x83, 0x21, 0x63, 0xce, 0x9f, 0x40,
	0x52, 0x65, 0x48, 0x0d, 0x44, 0xa6, 0x7e, 0xa8, 0x07, 0x70, 0x8b, 0xc2, 0xa8, 0xb6, 0x85, 0x5a,
	0x9a, 0xe1, 0x0c, 0x53, 0xc7, 0xc3, 0x84, 0xd6, 0xa8, 0xb5, 0xea, 0xaa, 0x7e, 0x38, 0x65, 0x00,
	0x0d, 0x62, 0xc1, 0xc3, 0x3f, 0xb1, 0xc8, 0xc6, 0x9b, 0x2c, 0x64, 0x92, 0x7d, 0x31, 0xdc, 0xc7,
	0x93, 0xc6, 0x37, 0x6a, 0xaf, 0x75, 0x50, 0x42, 0x86, 0x15, 0x62, 0xcf, 0x43, 0x7c, 0xf5, 0x69,
	0x99, 0xd4, 0xc9, 0x3d, 0xfb, 0x24, 0x23, 0x24, 0x72, 0x33, 0x83, 0x64, 0x7f, 0x60, 0x91, 0xcb,
	0x47, 0x81, 0x90, 0x70, 0x37, 0xc3, 0xb0, 0x5b, 0xfc, 0x92, 0xad, 0xe7, 0x81, 0x0a, 0xe7, 0x68,
	0xd2, 0x78, 0xad, 0xf6, 0xf5, 0x30, 0x10, 0x52, 0x6b, 0xaf, 0x3b, 0x44, 0x28, 0xa5, 0x38, 0x91,
	0xc0, 0xcd, 0x6d, 0x06, 0x00, 0x13, 0x94, 0xae, 0x67, 0x11, 0x2f, 0xea, 0x31, 0xa1, 0x80, 0xd8,
	0x53, 0x20, 0x1f, 0x5a, 0x84, 0xdc, 0x0f, 0xa2, 0xce, 0xdb, 0x8c, 0x0f, 0x18, 0xbf, 0x20, 0xe8,
	0x17, 0xfe, 0x4b, 0xe7, 0xbc, 0x35, 0x69, 0xbc, 0x52, 0xdb, 0xe9, 0x31, 0x49, 0x23, 0x26, 0x47,
	0x31, 0x1f, 0xd0, 0x30, 0xf6, 0x55, 0xf7, 0x14, 0x77, 0xe9, 0x08, 0x05, 0x2a, 0x44, 0x81, 0xa0,
	0x7e, 0xca, 0x39, 0x67, 0x91, 0x0c, 0xc7, 0x34, 0xdf, 0x4e, 0x29, 0xae, 0xed, 0x30, 0xf6, 0xef,
	0xf1, 0x49, 0x63, 0x60, 0x37, 0xc8, 0x55, 0x1c, 0xdd, 0xa8, 0x9a, 0xdd, 0x68, 0x8b, 0xf1, 0x33,
	0xc6, 0x9d, 0x17, 0x49, 0xe5, 0x5d, 0x26, 0x44, 0x40, 0x45, 0xdf, 0x8b, 0x06, 0xb5, 0xeb, 0xb8,
	0xc0, 0xef, 0x6f, 0x87, 0xec, 0x8c, 0x85, 0x77, 0xee, 0xd4, 0xfd, 0x78, 0xb8, 0x53, 0xbc, 0x53,
	0xbf, 0x7d, 0xb3, 0x60, 0x15, 0x76, 0xaa, 0x1e, 0x54, 0x54, 0x05, 0x66, 0xfb, 0x5d, 0x11, 0x47,
	0x77, 0xcf, 0x51, 0xbe, 0x5b, 0x48, 0xda, 0xed, 0x12, 0x9a, 0xfa, 0xe5, 0xff, 0x05, 0x00, 0x00,
	0xff, 0xff, 0xde, 0xbe, 0x56, 0x08, 0xaa, 0x1a, 0x00, 0x00,
}
